### ISSUE TITLE
議事録の会単位での要約生成機能（軽量LLM使用）

### ISSUE THREAD

**Issue by hironeko** [open-politicians-jp/gijiroku-search#21]
## 概要
議事録データを会単位でAI要約し、会議の概要を自動生成する機能を実装する。

### 1. 会単位での要約生成
- 同一会議（会期+委員会+回次）の全発言を統合
- 主要な議題・論点を抽出
- 政党間の対立点・合意点を整理
- 重要な発言者・発言内容をハイライト

### 2. 軽量LLM使用検討
- **候補1**: Llama 3.2 (1B/3B) - オープンソース
- **候補2**: Phi-3.5-mini - Microsoft製軽量モデル
- **候補3**: Gemma 2 (2B) - Google製軽量モデル
- **実行環境**: GitHub Actions (Linux runners)

### 1. LLMアーキテクチャ
```python
# scripts/uv-data-collection/summarize_meetings.py
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

class MeetingSummarizer:
    def __init__(self, model_name="microsoft/Phi-3.5-mini-instruct"):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(model_name)
    
    def summarize_meeting(self, speeches_data):
        # 会議データの前処理
        meeting_text = self.prepare_meeting_text(speeches_data)
        
        # プロンプト生成
        prompt = self.create_summary_prompt(meeting_text)
        
        # 要約生成
        summary = self.generate_summary(prompt)
        
        return summary
```

### 2. プロンプトエンジニアリング
```python
def create_summary_prompt(self, meeting_text):
    return f"""
以下は国会委員会の議事録です。この会議の要約を日本語で作成してください。

要約に含める要素：
1. 主要議題・審議内容
2. 政党別の主張・立場
3. 重要な質疑応答
4. 決議・採決結果（あれば）
5. 今後の課題・論点

議事録:
{meeting_text}

要約（300-500文字）:
"""
```

### 3. 実行環境・最適化
- **メモリ使用量**: 4GB未満（GitHub Actions制限内）
- **実行時間**: 会議あたり1-3分以内
- **バッチ処理**: 複数会議の並列処理
- **モデルキャッシュ**: 初回ダウンロード後のローカル保存

### 1. 要約データ形式
```json
{
  "meeting_id": "217_sangiin_yosan_05",
  "session": 217,
  "house": "sangiin",
  "committee": "予算委員会",
  "meeting_number": 5,
  "date": "2025-03-15",
  "summary": {
    "overview": "予算案の審議。防衛費増額を巡り与野党が対立...",
    "key_topics": ["防衛費", "社会保障", "税制改正"],
    "party_positions": {
      "自由民主党": "防衛費増額の必要性を強調",
      "立憲民主党": "社会保障予算削減に反対"
    },
    "important_exchanges": [
      {
        "questioner": "議員A",
        "topic": "防衛費",
        "summary": "防衛費の詳細な使途について質問"
      }
    ]
  },
  "generated_at": "2025-06-21T12:00:00Z",
  "model_used": "microsoft/Phi-3.5-mini-instruct",
  "token_count": 1500
}
```

### 2. GitHub Actions 統合
```yaml
# .github/workflows/summarize-meetings.yml
name: Generate Meeting Summaries
on:
  schedule:
    - cron: '0 6 * * 1'  # 毎週月曜 6:00 UTC
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install torch transformers accelerate
          
      - name: Generate summaries
        run: |
          python scripts/uv-data-collection/summarize_meetings.py
```

### 1. リソース制限対応
- **モデルサイズ**: 3B以下のパラメータ
- **量子化**: int8/int4量子化でメモリ削減
- **チャンク処理**: 長い議事録の分割処理

### 2. 品質向上策
- **プロンプト調整**: 日本の政治用語に特化
- **後処理**: 固有名詞の正規化
- **評価指標**: 人手評価との比較

### 3. エラーハンドリング
- OOM (Out of Memory) エラー対応
- API制限・タイムアウト処理
- 不完全な要約の検出・再試行

## 期待効果
- 大量議事録の効率的な概要把握
- 政策論点の可視化
- 研究者・記者の作業効率化
- 一般市民の政治参加促進

## 段階的実装計画
1. **Phase 1**: ローカル環境でのプロトタイプ開発
2. **Phase 2**: 小規模データでのテスト実行
3. **Phase 3**: GitHub Actions統合
4. **Phase 4**: 全議事録への適用

## 関連ファイル
- `scripts/uv-data-collection/summarize_meetings.py` (新規)
- `.github/workflows/summarize-meetings.yml` (新規)
- `frontend/types/summary.ts` (新規)
- `frontend/components/MeetingSummary.tsx` (新規)
