### ISSUE TITLE
デイリーデータ収集のスマートスキップ機能

### ISSUE THREAD

**Issue by hironeko** [open-politicians-jp/gijiroku-search#22]
## 概要
デイリーデータ収集において、新しいデータが存在しない場合に処理をスキップする機能を実装し、リソース効率化を図る。

## 問題背景
- 現在は毎日全データを再収集している
- 国会が開催されていない日も無駄に実行される
- GitHub Actions実行時間・リソースの浪費
- API呼び出し回数の無駄遣い

### 1. 更新チェック機能
- 最新データの収集日時を記録
- 各データソースの最終更新日を確認
- 新規データがない場合は処理スキップ

### 2. データソース別スキップ判定
- **議事録**: 国会会議録検索APIで最新日付確認
- **委員会ニュース**: 衆議院・参議院サイトの更新確認
- **法案情報**: 法案データベースの最終更新確認
- **質問主意書**: 質問データベースの最新提出日確認

### 1. 更新検知システム
```python
# scripts/uv-data-collection/update_checker.py
class UpdateChecker:
    def __init__(self):
        self.last_update_file = "data/last_updates.json"
        
    def check_for_updates(self, data_type):
        last_update = self.get_last_update(data_type)
        latest_available = self.get_latest_available_date(data_type)
        
        return latest_available > last_update
    
    def get_latest_available_date(self, data_type):
        if data_type == "speeches":
            return self.check_kokkai_api_latest()
        elif data_type == "committee_news":
            return self.check_committee_sites_latest()
        elif data_type == "bills":
            return self.check_bills_db_latest()
        elif data_type == "questions":
            return self.check_questions_db_latest()
    
    def update_last_processed(self, data_type, date):
        # 処理完了後に最終更新日を記録
        pass
```

### 2. メインスクリプト統合
```python
# scripts/uv-data-collection/daily_data_collection.py
def main():
    checker = UpdateChecker()
    
    # 各データタイプの更新チェック
    data_types = ["speeches", "committee_news", "bills", "questions"]
    
    for data_type in data_types:
        if checker.check_for_updates(data_type):
            print(f"新しい{data_type}データを検出。収集を開始...")
            collect_data(data_type)
            checker.update_last_processed(data_type, datetime.now())
        else:
            print(f"{data_type}に新しいデータなし。スキップします。")
```

### 3. 最終更新記録ファイル
```json
{
  "last_updates": {
    "speeches": {
      "last_processed": "2025-06-20T03:00:00Z",
      "last_available": "2025-06-20T15:30:00Z",
      "items_processed": 1250
    },
    "committee_news": {
      "last_processed": "2025-06-19T03:00:00Z",
      "last_available": "2025-06-19T18:00:00Z",
      "items_processed": 15
    },
    "bills": {
      "last_processed": "2025-06-18T03:00:00Z",
      "last_available": "2025-06-18T10:00:00Z",
      "items_processed": 8
    },
    "questions": {
      "last_processed": "2025-06-17T03:00:00Z",
      "last_available": "2025-06-17T16:00:00Z",
      "items_processed": 3
    }
  },
  "updated_at": "2025-06-21T03:00:00Z"
}
```

### 1. 国会会議録検索API
```python
def check_kokkai_api_latest():
    # 最新会期の最新日付を取得
    params = {
        'maximumRecords': 1,
        'startRecord': 1,
        'recordPacking': 'xml',
        'from': '2025-01-01'  # 今年から
    }
    response = requests.get(KOKKAI_API_URL, params=params)
    # XMLから最新の会議日を抽出
    return parse_latest_date(response.content)
```

### 2. 委員会サイト更新確認
```python
def check_committee_sites_latest():
    # 衆議院・参議院の委員会ページのLast-Modifiedヘッダーチェック
    # または最新の委員会開催予定から推定
    pass
```

### 1. ワークフロー修正
```yaml
# .github/workflows/data-collection.yml
jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
      
    steps:
      - name: Check for updates
        id: check
        run: |
          # 更新チェック実行
          if python scripts/uv-data-collection/update_checker.py; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi
  
  collect-data:
    needs: check-updates
    if: needs.check-updates.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      # 実際のデータ収集処理
```

### 2. 通知機能
```yaml
- name: Notify skip
  if: needs.check-updates.outputs.should-run == 'false'
  run: |
    echo "## 📊 データ収集スキップ" >> $GITHUB_STEP_SUMMARY
    echo "新しいデータが見つからないため、今日の収集をスキップしました。" >> $GITHUB_STEP_SUMMARY
    echo "最終更新: $(cat data/last_updates.json | jq -r '.updated_at')" >> $GITHUB_STEP_SUMMARY
```

### 1. リソース効率化
- GitHub Actions実行時間の削減（推定30-50%）
- API呼び出し回数の削減
- ストレージ使用量の最適化

### 2. 運用改善
- 無駄な処理の排除
- 実際に更新があった時のみ通知
- ログの見やすさ向上

### 3. 国会スケジュール対応
- 国会閉会中の自動スキップ
- 委員会開催日以外のスキップ
- 祝日・年末年始の考慮

## 技術詳細
- **更新判定精度**: 分単位での比較
- **API制限対応**: チェック用の軽量API呼び出し
- **フォールバック**: チェック失敗時は通常実行
- **ログ出力**: スキップ理由の詳細記録

## 関連ファイル
- `scripts/uv-data-collection/update_checker.py` (新規)
- `scripts/uv-data-collection/daily_data_collection.py`
- `.github/workflows/data-collection.yml`
- `data/last_updates.json` (新規)
