### ISSUE TITLE
参議院法案データの収集機能実装

### ISSUE THREAD

**Issue by hironeko** [open-politicians-jp/gijiroku-search#25]
## 概要
参議院公式サイトから法案データを収集し、既存の法案検索システムに統合する機能を実装する。

## データソース
**参議院法案一覧**: https://www.sangiin.go.jp/japanese/joho1/kousei/gian/217/gian.htm

### サイト構造分析
- 会期別の法案一覧ページ
- 委員会別の分類あり
- 法案番号、法案名、提出者、審議状況等の情報
- 法案詳細ページへのリンク

### 1. 参議院法案データ収集
- 会期別法案一覧の取得
- 法案詳細情報の抽出
- 委員会審議状況の取得
- 過去会期データの遡及収集

### 2. データ統合
- 既存の衆議院法案データとの統合
- 重複法案の検出・統合処理
- 統一フォーマットでのデータ保存

### 3. 過去データ対応
- 過去会期の一括収集機能
- 段階的な遡及処理（会期単位）
- 既存データとの差分更新

### 1. 参議院法案収集スクリプト
```python
# scripts/uv-data-collection/collect_sangiin_bills.py
class SangiinBillsCollector:
    def __init__(self):
        self.base_url = "https://www.sangiin.go.jp"
        self.session_url_template = "/japanese/joho1/kousei/gian/{session}/gian.htm"
        
    def collect_session_bills(self, session_number):
        """指定会期の法案を収集"""
        url = self.base_url + self.session_url_template.format(session=session_number)
        response = requests.get(url)
        bills = self.parse_bills_list(response.content)
        
        # 詳細情報を取得
        for bill in bills:
            bill['details'] = self.get_bill_details(bill['detail_url'])
            
        return bills
    
    def parse_bills_list(self, html_content):
        """法案一覧ページから法案情報を抽出"""
        soup = BeautifulSoup(html_content, 'html.parser')
        bills = []
        
        # テーブル構造を解析して法案情報を抽出
        for row in soup.find_all('tr'):
            bill_data = self.extract_bill_from_row(row)
            if bill_data:
                bills.append(bill_data)
                
        return bills
    
    def get_bill_details(self, detail_url):
        """法案詳細ページから追加情報を取得"""
        response = requests.get(self.base_url + detail_url)
        return self.parse_bill_details(response.content)
```

### 2. データ構造統一
```json
{
  "bill_id": "sangiin_217_001",
  "source": "sangiin",
  "session": 217,
  "bill_number": "第1号",
  "bill_name": "○○に関する法律案",
  "submitter": "内閣",
  "submitter_type": "government|member",
  "committee": "厚生労働委員会",
  "status": "審議中",
  "submission_date": "2025-01-15",
  "deliberation_history": [
    {
      "date": "2025-01-20",
      "committee": "厚生労働委員会",
      "action": "趣旨説明"
    }
  ],
  "related_documents": [
    {
      "type": "bill_text",
      "url": "https://www.sangiin.go.jp/...",
      "title": "法案本文"
    }
  ],
  "summary": "法案の概要...",
  "collected_at": "2025-06-21T12:00:00Z"
}
```

### 3. 既存システムとの統合
```python
# scripts/uv-data-collection/integrate_bills_data.py
class BillsIntegrator:
    def merge_house_data(self, shugiin_bills, sangiin_bills):
        """衆参両院の法案データを統合"""
        merged_bills = []
        
        # 重複検出（法案名・会期での照合）
        for s_bill in sangiin_bills:
            duplicate = self.find_duplicate_bill(s_bill, shugiin_bills)
            if duplicate:
                merged_bill = self.merge_bill_data(s_bill, duplicate)
                merged_bills.append(merged_bill)
            else:
                merged_bills.append(s_bill)
                
        return merged_bills
    
    def find_duplicate_bill(self, sangiin_bill, shugiin_bills):
        """重複法案の検出"""
        for h_bill in shugiin_bills:
            if self.is_same_bill(sangiin_bill, h_bill):
                return h_bill
        return None
```

### 1. 会期別遡及収集
```python
# scripts/uv-data-collection/collect_historical_sangiin_bills.py
def collect_historical_bills(start_session=200, end_session=217):
    """過去会期の法案を遡及収集"""
    collector = SangiinBillsCollector()
    
    for session in range(start_session, end_session + 1):
        try:
            print(f"第{session}回国会の法案を収集中...")
            bills = collector.collect_session_bills(session)
            
            # データ保存
            filename = f"sangiin_bills_{session}.json"
            save_bills_data(bills, filename)
            
            # レート制限
            time.sleep(2)
            
        except Exception as e:
            print(f"第{session}回国会の収集でエラー: {e}")
            continue
```

### 2. GitHub Actions 分離
```yaml
# .github/workflows/collect-sangiin-bills-historical.yml
name: Collect Historical Sangiin Bills
on:
  workflow_dispatch:
    inputs:
      start_session:
        description: '開始会期'
        default: '200'
      end_session:
        description: '終了会期'
        default: '216'
      batch_size:
        description: '一度に処理する会期数'
        default: '5'

jobs:
  collect-historical:
    runs-on: ubuntu-latest
    steps:
      - name: Collect bills by session
        run: |
          for session in $(seq ${{ inputs.start_session }} ${{ inputs.end_session }}); do
            python scripts/uv-data-collection/collect_historical_sangiin_bills.py --session $session
            if [ $((session % ${{ inputs.batch_size }})) -eq 0 ]; then
              sleep 30  # バッチ間の休憩
            fi
          done

# .github/workflows/collect-sangiin-bills-daily.yml  
name: Collect Recent Sangiin Bills
on:
  schedule:
    - cron: '0 4 * * 1-5'  # 平日朝4時
```

### 1. 委員会ページの活用
- 各委員会の審議中法案一覧
- 委員会別の審議履歴
- より詳細な審議状況の取得

### 2. 実装オプション
```python
def collect_by_committee(self, session, committee_name):
    """委員会別の法案収集"""
    committee_url = f"/japanese/joho1/kousei/gian/{session}/{committee_name}/"
    # 委員会別ページから法案を収集
```

### 1. 法案テキスト取得
- 法案本文PDFのダウンロード
- テキスト抽出・構造化
- 検索可能な形式での保存

### 2. 審議履歴の詳細化
- 委員会での審議日程
- 質疑応答の記録
- 採決結果の記録

### 3. 関連資料の収集
- 参考資料・説明資料
- 附帯決議
- 修正案・対案

### 1. 既存検索の拡張
- 院別フィルター（衆議院・参議院・両院）
- 提出者別検索（内閣・議員提出）
- 委員会別検索

### 2. 表示改善
- 審議経過の視覚化
- 両院での進捗状況表示
- 関連法案の表示

## 期待効果
- 参議院法案情報の網羅的収集
- 両院での法案審議状況の一元管理
- 立法プロセスの可視化向上
- 政策研究・報道活動の支援

### 1. スクレイピング仕様
- **レート制限**: 2-3秒間隔
- **エラーハンドリング**: 個別ページ失敗時の継続処理
- **データ検証**: 必須フィールドの存在確認

### 2. データ保存
- **ファイル形式**: JSON（会期別・統合版）
- **保存先**: `frontend/public/data/bills/sangiin/`
- **命名規則**: `sangiin_bills_session_{session}.json`

### 3. 統合処理
- **重複検出**: 法案名・提出者・提出日での照合
- **マージ戦略**: 詳細情報の統合、審議履歴の結合
- **データ整合性**: 両院データの不整合検出・報告

### 新規作成
- `scripts/uv-data-collection/collect_sangiin_bills.py`
- `scripts/uv-data-collection/collect_historical_sangiin_bills.py`
- `scripts/uv-data-collection/integrate_bills_data.py`
- `.github/workflows/collect-sangiin-bills-historical.yml`
- `.github/workflows/collect-sangiin-bills-daily.yml`

### 修正対象
- `scripts/uv-data-collection/collect_bills.py` (統合処理追加)
- `frontend/components/BillsResults.tsx` (院別表示)
- `frontend/types/index.ts` (Bill型拡張)

## 参考リンク
- 参議院法案情報: https://www.sangiin.go.jp/japanese/joho1/kousei/gian/
- 法制局資料: 法案作成・審議プロセスの参考資料
