### ISSUE TITLE
過去データと最新データのcron分離（要約生成・法案収集対応）

### ISSUE THREAD

**Issue by hironeko** [open-politicians-jp/gijiroku-search#26]
## 概要
過去データの一括処理と最新データのデイリー処理を分離し、効率的なデータ収集・処理システムを構築する。

## 背景
- 要約生成（Issue #21）では過去の大量データ処理が必要
- 参議院法案収集（Issue #25）でも過去会期の遡及処理が必要
- 一度に大量処理すると実行時間・リソース制限に抵触
- デイリー処理と過去データ処理では最適化方針が異なる

### 1. 過去データ処理（Historical Data Processing）
- **実行頻度**: 手動実行（workflow_dispatch）
- **処理対象**: 指定期間の過去データ
- **バッチサイズ**: 小さく制限（実行時間対応）
- **実行時間**: 長時間（1-2時間想定）

### 2. 最新データ処理（Recent Data Processing）  
- **実行頻度**: デイリー自動実行
- **処理対象**: 前回実行以降の新しいデータ
- **バッチサイズ**: 通常サイズ
- **実行時間**: 短時間（30分以内）

### 1. GitHub Actions ワークフロー分離
```yaml
# .github/workflows/process-historical-data.yml
name: Process Historical Data
on:
  workflow_dispatch:
    inputs:
      data_type:
        description: 'データ種別'
        type: choice
        options:
          - 'summaries'
          - 'sangiin_bills'
          - 'all'
      start_date:
        description: '開始日 (YYYY-MM-DD)'
        required: true
      end_date:
        description: '終了日 (YYYY-MM-DD)'
        required: true
      batch_size:
        description: 'バッチサイズ'
        default: '10'

jobs:
  process-summaries:
    if: inputs.data_type == 'summaries' || inputs.data_type == 'all'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Process meeting summaries
        run: |
          python scripts/uv-data-collection/summarize_historical_meetings.py \
            --start-date ${{ inputs.start_date }} \
            --end-date ${{ inputs.end_date }} \
            --batch-size ${{ inputs.batch_size }}

  process-bills:
    if: inputs.data_type == 'sangiin_bills' || inputs.data_type == 'all'
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Collect historical bills
        run: |
          python scripts/uv-data-collection/collect_historical_sangiin_bills.py \
            --start-date ${{ inputs.start_date }} \
            --end-date ${{ inputs.end_date }}

# .github/workflows/process-recent-data.yml
name: Process Recent Data
on:
  schedule:
    - cron: '0 3 * * 1-5'  # 平日朝3時
  workflow_dispatch:

jobs:
  process-recent:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Generate recent summaries
        run: python scripts/uv-data-collection/summarize_recent_meetings.py
        
      - name: Collect recent bills
        run: python scripts/uv-data-collection/collect_recent_sangiin_bills.py
```

### 2. 処理スクリプトの分離
```python
# scripts/uv-data-collection/process_historical_data.py
class HistoricalDataProcessor:
    def __init__(self, batch_size=10):
        self.batch_size = batch_size
        self.progress_file = "data/historical_progress.json"
    
    def process_date_range(self, start_date, end_date, data_type):
        """指定期間のデータを段階的に処理"""
        progress = self.load_progress()
        
        # 日付範囲を小さなバッチに分割
        date_batches = self.create_date_batches(start_date, end_date)
        
        for batch in date_batches:
            if self.is_batch_completed(batch, progress):
                continue
                
            try:
                self.process_batch(batch, data_type)
                self.mark_batch_completed(batch, progress)
                
                # バッチ間の休憩
                time.sleep(30)
                
            except Exception as e:
                self.log_batch_error(batch, e)
                continue
    
    def create_date_batches(self, start_date, end_date):
        """日付範囲を処理可能なバッチに分割"""
        batches = []
        current_date = start_date
        
        while current_date <= end_date:
            batch_end = min(
                current_date + timedelta(days=7),  # 1週間単位
                end_date
            )
            batches.append((current_date, batch_end))
            current_date = batch_end + timedelta(days=1)
            
        return batches

# scripts/uv-data-collection/process_recent_data.py  
class RecentDataProcessor:
    def __init__(self):
        self.last_processed_file = "data/last_processed.json"
    
    def process_recent_data(self):
        """前回処理以降の新しいデータを処理"""
        last_processed = self.get_last_processed_date()
        current_date = datetime.now().date()
        
        if last_processed >= current_date:
            print("処理対象の新しいデータなし")
            return
            
        # 最新データの処理
        self.process_summaries_since(last_processed)
        self.process_bills_since(last_processed)
        
        # 最終処理日を更新
        self.update_last_processed_date(current_date)
```

### 3. 進捗管理システム
```python
# scripts/uv-data-collection/progress_manager.py
class ProgressManager:
    def __init__(self, process_type):
        self.process_type = process_type
        self.progress_file = f"data/progress_{process_type}.json"
    
    def save_progress(self, batch_info, status, details=None):
        """処理進捗を保存"""
        progress = self.load_progress()
        
        progress[batch_info['id']] = {
            'status': status,  # 'pending', 'processing', 'completed', 'failed'
            'start_time': batch_info.get('start_time'),
            'end_time': datetime.now().isoformat() if status in ['completed', 'failed'] else None,
            'details': details,
            'retry_count': batch_info.get('retry_count', 0)
        }
        
        self.save_progress_file(progress)
    
    def get_failed_batches(self):
        """失敗したバッチの一覧を取得"""
        progress = self.load_progress()
        return [
            batch_id for batch_id, info in progress.items()
            if info['status'] == 'failed' and info['retry_count'] < 3
        ]
    
    def retry_failed_batches(self):
        """失敗したバッチの再試行"""
        failed_batches = self.get_failed_batches()
        for batch_id in failed_batches:
            try:
                self.process_batch_by_id(batch_id)
            except Exception as e:
                self.increment_retry_count(batch_id)
```

### 1. データ種別ごとの最適化
```python
BATCH_CONFIGURATIONS = {
    'meeting_summaries': {
        'batch_size': 5,        # 5会議/バッチ
        'max_execution_time': 45,  # 45分
        'memory_limit': '3GB'
    },
    'sangiin_bills': {
        'batch_size': 2,        # 2会期/バッチ  
        'max_execution_time': 30,  # 30分
        'memory_limit': '2GB'
    },
    'speeches_processing': {
        'batch_size': 1000,     # 1000件/バッチ
        'max_execution_time': 20,  # 20分
        'memory_limit': '2GB'
    }
}
```

### 2. 動的バッチサイズ調整
```python
class AdaptiveBatchProcessor:
    def adjust_batch_size(self, last_execution_time, last_memory_usage):
        """前回の実行時間・メモリ使用量に基づきバッチサイズを調整"""
        if last_execution_time > 40:  # 40分超過
            self.batch_size = max(1, self.batch_size // 2)
        elif last_execution_time < 15:  # 15分未満
            self.batch_size = min(20, self.batch_size * 1.5)
            
        return self.batch_size
```

### 1. 段階的再試行
```python
def process_with_retry(self, batch, max_retries=3):
    """段階的再試行機能"""
    for attempt in range(max_retries):
        try:
            return self.process_batch(batch)
        except MemoryError:
            # メモリ不足の場合はバッチサイズを半分に
            batch = self.split_batch(batch)
            continue
        except TimeoutError:
            # タイムアウトの場合は処理時間を延長
            self.extend_timeout()
            continue
        except Exception as e:
            if attempt == max_retries - 1:
                raise e
            time.sleep(60 * (attempt + 1))  # 段階的待機
```

### 2. 部分的失敗への対応
```python
def process_batch_with_tolerance(self, batch):
    """部分的失敗を許容した処理"""
    results = []
    failures = []
    
    for item in batch:
        try:
            result = self.process_item(item)
            results.append(result)
        except Exception as e:
            failures.append({'item': item, 'error': str(e)})
    
    # 成功した分は保存、失敗分は後で再試行
    if results:
        self.save_results(results)
    if failures:
        self.log_failures(failures)
    
    return len(results), len(failures)
```

### 1. 過去データ処理
- **実行方法**: 手動トリガー（GitHub Actions UI）
- **実行タイミング**: 新機能実装後、データ拡張時
- **実行時間帯**: 夜間・週末（リソース競合回避）

### 2. 最新データ処理
- **議事録要約**: 毎週月曜 7:00（新しい会議の要約生成）
- **法案収集**: 毎日 4:00（最新の法案状況確認）
- **統合処理**: 毎日 5:00（各データの統合・整理）

### 1. 処理状況の可視化
```python
def generate_progress_report(self):
    """処理進捗レポートの生成"""
    progress = self.load_progress()
    
    report = {
        'total_batches': len(progress),
        'completed': sum(1 for p in progress.values() if p['status'] == 'completed'),
        'failed': sum(1 for p in progress.values() if p['status'] == 'failed'),
        'processing_time': self.calculate_total_time(progress),
        'estimated_remaining': self.estimate_remaining_time(progress)
    }
    
    return report
```

### 2. 失敗通知システム
```yaml
- name: Notify on failure
  if: failure()
  run: |
    echo "## ❌ 過去データ処理失敗" >> $GITHUB_STEP_SUMMARY
    echo "バッチ処理中にエラーが発生しました。ログを確認してください。" >> $GITHUB_STEP_SUMMARY
    python scripts/utils/send_failure_notification.py
```

## 期待効果
- **リソース効率化**: 適切なバッチサイズで実行時間制限内での処理
- **障害耐性**: 部分的失敗や再試行による安定性向上  
- **運用効率**: 過去データと最新データの最適化された処理
- **スケーラビリティ**: 新しいデータタイプの追加容易性

### 新規作成
- `.github/workflows/process-historical-data.yml`
- `.github/workflows/process-recent-data.yml`
- `scripts/uv-data-collection/process_historical_data.py`
- `scripts/uv-data-collection/process_recent_data.py`
- `scripts/uv-data-collection/progress_manager.py`
- `data/progress_*.json` (進捗管理ファイル)

### 修正対象
- 既存のcronジョブ（分離・統合）
- データ処理スクリプト（バッチ処理対応）

## 依存関係
- Issue #21（議事録要約生成）
- Issue #25（参議院法案収集）
- その他の大量データ処理機能
