### ISSUE TITLE
Create Release Tag and Deployment GitHub Actions Workflow

### ISSUE THREAD

**Issue by hironeko** [open-politicians-jp/gijiroku-search#28]
## Overview
Create automated release tagging and deployment workflow for managing releases with GitHub Actions.

### 1. Release Tag Creation Workflow
- Automated release tag creation (v1.0.0, v1.0.1, etc.)
- Tag-based deployment triggers
- Release notes generation
- Version management automation

### 2. Deployment Workflow
- Deploy on release tag creation
- GitHub Pages deployment
- Static site generation optimization
- Build artifact management

### 1. Release Workflow
```yaml
# .github/workflows/release.yml
name: Create Release
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment type'
        type: choice
        options:
          - 'patch'
          - 'minor' 
          - 'major'
        default: 'patch'
      
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get next version
      - name: Create release tag
      - name: Generate release notes
      - name: Create GitHub release
```

### 2. Deploy Workflow
```yaml
# .github/workflows/deploy.yml
name: Deploy to GitHub Pages
on:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Next.js
      - name: Deploy to GitHub Pages
```

## Expected Outcomes
- Automated version management
- Consistent deployment process
- Release history tracking
- Simplified release workflow

## Related Files
- `.github/workflows/release.yml` (new)
- `.github/workflows/deploy.yml` (new)
- `package.json` (version management)
