### ISSUE TITLE
政党マニフェスト収集の手動化・週次自動実行停止

### ISSUE THREAD

**Issue by hironeko** [open-politicians-jp/gijiroku-search#87]
## 概要
政党マニフェスト収集を週次自動実行から手動実行に変更し、不要な自動更新を停止

## 背景
- マニフェストは頻繁に更新されるものではない
- 週次自動実行によるリソース消費が不要
- 政治的なタイミング（選挙期間、政策発表時）での手動実行が適切
- データ収集処理時間の最適化の一環

### 1. GitHub Actions設定変更
- マニフェスト収集の週次cron実行を無効化
- 手動実行(`workflow_dispatch`)のみに変更
- 他のデータ収集には影響しない

### 2. 実行タイミングの明確化
**手動実行が必要な場合:**
- 選挙期間中（参院選2025など）
- 政党の政策発表・マニフェスト更新時
- 重要な政治イベント前後
- 四半期ごとの定期メンテナンス

### 3. ドキュメント更新
- CLAUDE.mdの自動実行ルール更新
- README.mdの手動実行手順追加
- 実行タイミングガイドラインの作成

### GitHub Actions変更
```yaml
# 変更前
on:
  schedule:
    - cron: '0 3 * * 0'  # 毎週日曜日午前3時
  workflow_dispatch:

# 変更後  
on:
  workflow_dispatch:  # 手動実行のみ
```

### 実行コマンド
```bash
# 手動実行方法
gh workflow run "政党マニフェスト収集" --ref main

# または直接スクリプト実行
cd scripts/uv-data-collection
uv run python collect_real_manifestos.py
```

## 期待効果
- **リソース節約**: 週次不要実行の停止
- **適切なタイミング**: 政治的に意味のある時期での更新
- **処理時間短縮**: 全体的なデータ収集時間の最適化
- **保守性向上**: 明確な実行ルールによる運用改善

## 影響範囲
- ✅ 影響なし: 議事録、質問主意書、提出法案の自動収集
- ✅ 影響なし: 週次データ整理
- ⚠️ 変更あり: マニフェストデータの更新頻度
- ✅ 改善: 全体的な処理効率

## 関連Issue
- 関連: #86 データ収集重複問題の修正と最適化
- 参照: #83 参院選2025候補者データ収集システム実装
